const days = [
  {dayNumber: '25', status: 'past'},
  {dayNumber: '26', status: 'past'},
  {dayNumber: '27', status: 'past'},
  {dayNumber: '28', status: 'past'},
  {dayNumber: '29', status: 'past'},
  {dayNumber: '30', status: 'past'},
  {dayNumber: '31', status: 'past'},
  {dayNumber: '1', status: 'disabled'},
  {dayNumber: '2', status: 'disabled'},
  {dayNumber: '3', status: 'disabled'},
  {dayNumber: '4', status: 'disabled'},
  {dayNumber: '5', status: 'disabled'},
  {dayNumber: '6', status: 'disabled'},
  {dayNumber: '7', status: 'disabled'},
  {dayNumber: '8', status: 'disabled'},
  {dayNumber: '9', status: 'disabled'},
  {dayNumber: '10', status: 'checked'},
  {dayNumber: '11', status: 'current'},
  {dayNumber: '12', status: 'current'},
  {dayNumber: '13', status: 'current'},
  {dayNumber: '14', status: 'current'},
  {dayNumber: '15', status: 'current'},
  {dayNumber: '16', status: 'current'},
  {dayNumber: '17', status: 'current'},
  {dayNumber: '18', status: 'current'},
  {dayNumber: '19', status: 'current'},
  {dayNumber: '20', status: 'current'},
  {dayNumber: '21', status: 'current'},
  {dayNumber: '22', status: 'current'},
  {dayNumber: '23', status: 'current'},
  {dayNumber: '24', status: 'current'},
  {dayNumber: '25', status: 'current'},
  {dayNumber: '26', status: 'current today'},
  {dayNumber: '27', status: 'current'},
  {dayNumber: '28', status: 'current'},
  {dayNumber: '29', status: 'current'},
  {dayNumber: '30', status: 'current'},
  {dayNumber: '1', status: 'disabled'},
  {dayNumber: '2', status: 'disabled'},
  {dayNumber: '3', status: 'disabled'},
  {dayNumber: '4', status: 'disabled'},
  {dayNumber: '5', status: 'disabled'},
]

export default days